### PR TITLE
Fix saving assets on CraftCMS 3.1 and getFolderId returning 0 when there are subfolders. 

### LINKED ISSUE #70: Embed not saving
Hi,

This was working fine until today which is odd, but we cannot embed anything now.

So, go to assets, click "Embed", paste in youtube or vimeo url and hit save. The modal goes away but nothing is saved in the asset location.

There are no errors logged so i have no idea what is the issue here!

Thanks

John

### PR DESCRIPTION
**Pull request by kyle51north**
Assets now get saved in the correct folder when there are subfolders defined on the field. Fixes #70.

### CODE REVIEW

**Comment by nicolasbinet** [comment]
this one saved us lots of trouble

**Comment by keithmancuso** [comment]
Any chance of seeing this merged into master anytime soon?

**Comment by nicolasbinet** [comment]
@keithmancuso we did add @kyle51north repository to our composer.json 

    "repositories": [  
      {  
        "type": "vcs",   
        "url": "git@github.com:kyle51north/craft-embedded-assets.git"   
      } .  
    ],

**Comment by kyle51north** [comment]
@benjamminf Any chance you could have a look at this soon?

I can confirm this works on production installations. More people are starting to use my fork because of this fix.

**Comment by keithmancuso** [comment]
hey @kyle51north i wasnt able to get your fork loading?  Amy i missing a step?

I added the suggestion above to the top level of composer.json 

```"repositories": [  
  {  
    "type": "vcs",   
    "url": "git@github.com:kyle51north/craft-embedded-assets.git"   
  } 
],   ```


i also tried changing the require to say `"kyle51north/craft-embedded-assets": "1.0.2",` instead of   `"benjamminf/craft-embedded-assets": "1.0.2",` and still no luck?


Any help would be appreciated until @benjamminf is able to merge this into master

**Comment by nicolasbinet** [comment]
@keithmancuso I forgot to add that you avec to specify the version as dev-master

`"benjamminf/craft-embedded-assets": "dev-master",`

instead of

`"benjamminf/craft-embedded-assets": "1.0.2",`

**Comment by nicolasbinet** [comment]
You're right. Same here.
I've found a solution

In client/src/main.js, replace 

```
const getFolderId = () => {
    const split = this.getDefaultSourceKey().split('/').pop().split(':');
    return split[split.length - 1] | 0;
};

```
By

```
const getFolderId = () => {
    const $source = this._getSourceByKey(this.sourceKey);
    return $source.data('folder-id');
};
```

But, I'm not sure we can use the _getSourceByKey, as it's prefixed with an underscore.

**Comment by kyle51north** [comment]
@nicolasbinet @keithmancuso 

Thanks for the quick research! However, it does not work for subfolders in my environment. Haven't had too much time to check.

Seems since Craft CMS 3.1 the getDefaultSourceKey() returns a different string with UUIDs instead of ids now. I hope I can have a quick look at this issue tommorrow.

**Comment by boboldehampsink** [comment]
+1

**Comment by kyle51north** [comment]
@keithmancuso @nicolasbinet 

I've pushed a possible fix for 3.1 to my branch, but I haven't had the time to test this on 3.0.

**Comment by 24HOURSMEDIA** [comment]
@kyle51north Seems to work on craft 3.1 though.- you saved my day and many hours explaining why we couldn't upgrade.

@benjamminf It is a nice plugin... but a pity Kyle's branches don't get merged

**Comment by jamiewade** [comment]
Can confirm this is working great on `3.1.x`, thanks so much 😄

**Comment by helbnt** [comment]
@kyle51north thanks so much - this was driving me crazy and after a frustrating morning, I found your update. Works like a charm.

**Comment by ttempleton** [comment]
Thanks @kyle51north!  Could you please revert your changes to the style of `client/src/main.js` to match the project's JS style, then we'll merge this into the `dev` branch and we'll look to have a new release within the next week.

**Comment by kyle51north** [comment]
@ttempleton Done!

**Comment by ttempleton** [comment]
@kyle51north Thanks!

**Pull request merged**
